version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'my-app-db'
       MYSQL_USER: 'myuser'
       MYSQL_PASSWORD: 'mypassword'
       MYSQL_ROOT_PASSWORD: 'rootpassword'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
#    command: /bin/bash
    volumes:
      - ./my_projects:/my_projects
    ports:
      - "8000:8000"
    depends_on:
      - "db"

