version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db/:/data/db
    command: --quiet --logpath /dev/null 
  django:
    build: ./django_project
    volumes:
      - ./django_project:/app
      - ./flutter_project/build/web:/flutter_project/build/web
    depends_on:
      - mongo
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py initializedevserver && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000


