version: '3'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db/:/data/db
  django:
    build: ./django-project
    volumes:
      - ./django-project:/app
    depends_on:
      - mongo
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000


