# Generated by Django 3.1.4 on 2021-04-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
