# Generated by Django 3.0.5 on 2021-06-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivedhanamapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivedhanam',
            name='reply_recieved',
        ),
        migrations.AddField(
            model_name='nivedhanam',
            name='status',
            field=models.CharField(choices=[('NR', 'Nivedhanam Recieved')], default='NR', max_length=2),
        ),
    ]
