# Generated by Django 3.0.5 on 2021-09-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivedhanamapp', '0002_auto_20210813_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivedhanam',
            name='name',
            field=models.TextField(),
        ),
    ]
