# Generated by Django 3.0.5 on 2021-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivedhanamapp', '0002_auto_20210629_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivedhanam',
            name='status',
            field=models.CharField(choices=[('Nivedhanam Recieved', 'Nivedhanam Recieved')], default='Nivedhanam Recieved', max_length=50),
        ),
    ]
