# Generated by Django 3.0.5 on 2021-06-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivedhanamapp', '0003_auto_20210629_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivedhanam',
            name='status',
            field=models.CharField(choices=[('nivedhanam recieved', 'Nivedhanam Recieved')], default='nivedhanam recieved', max_length=50),
        ),
    ]
