# Generated by Django 3.0.5 on 2021-06-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivedhanamapp', '0004_auto_20210629_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivedhanam',
            name='status',
            field=models.CharField(choices=[('recieved', 'Nivedhanam Recieved'), ('processing', 'Nivedhanam Processing'), ('approved', 'Nivedhanam Approved')], default='recieved', max_length=50),
        ),
    ]
