# Generated by Django 3.0.5 on 2021-06-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivedhanamapp', '0006_auto_20210629_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivedhanam',
            name='amount_sanctioned',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='nivedhanam',
            name='mobile',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='nivedhanam',
            name='pincode',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
