# Generated by Django 3.0.5 on 2021-07-08 16:52

from django.db import migrations, models
import djongo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('nivedhanamapp', '0007_auto_20210630_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='page_number',
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan',
            field=models.FileField(storage=djongo.storage.GridFSStorage(base_url='scan_collection/', collection='scan_collection'), upload_to='scan_collection'),
        ),
    ]
