# Generated by Django 3.0.5 on 2021-05-31 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivedhanam',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('SI_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('letterno', models.IntegerField()),
                ('date', models.DateField()),
                ('reply_recieved', models.CharField(max_length=200)),
                ('amount_sanctioned', models.FloatField()),
                ('date_sanctioned', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
