# Generated by Django 3.0.5 on 2021-05-04 15:57

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nivedhanam',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('SI_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('letterno', models.IntegerField()),
                ('date', models.DateField()),
                ('reply_recieved', models.CharField(max_length=200)),
                ('amount_sanctioned', models.FloatField()),
                ('date_sanctioned', models.DateField()),
                ('remarks', models.TextField()),
            ],
        ),
    ]
